### ISSUE TITLE
dwarf decreased size allows infinite breathing underwater.

### ISSUE THREAD

**Issue by makazis** [FlamingTaco113/origins-datapack#8]
By swimming up into a block, it not only gives perfect vision of an underwater structure, but also allows the dwarf to refill on air reserves. I don't know how to fix this, just wanted to let you know. Dwarf OP

**Comment by FlamingTaco113** [comment]
I think this may be an issue with the Minecraft scale attribute itself, and likely can't be fixed unless patched by Mojang.
